# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-25 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='main.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
